# Generated by Django 4.2.20 on 2025-04-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration', models.FloatField(help_text='Продолжительность курса в месяцах.', verbose_name='Длительность')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Стоимость')),
                ('language', models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('js', 'JavaScript'), ('csharp', 'C#'), ('go', 'Go')], max_length=20, verbose_name='Язык')),
                ('type', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('test', 'Test'), ('devops', 'Devops'), ('security', 'Security'), ('ml', 'ML')], max_length=20, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
    ]
