# Generated by Django 4.2.20 on 2025-04-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_teacher_alter_course_options_course_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.PositiveIntegerField(help_text='в годах', verbose_name='Возраст'),
        ),
    ]
