# Generated by Django 4.2.20 on 2025-04-16 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blog_payment_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='type',
            new_name='skill',
        ),
    ]
