# Generated by Django 4.2.20 on 2025-04-18 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_type_course_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='annotation',
            field=models.TextField(default=1, verbose_name='Аннотация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(db_index=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='main.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Эл. почта'),
        ),
    ]
